# Generated by Django 5.2 on 2025-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
    ]
