# Generated by Django 5.2 on 2025-04-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_auteur_id_alter_article_categorie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
